{{- if .Values.services.grafana }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-prometheus:9090
        isDefault: true
{{- end }}
