{{- if and .Values.services.ueIdentity .Values.ueIdentity.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ue-identity-config
  labels:
    app.kubernetes.io/name: ue-identity
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    httpPort: {{ .Values.ueIdentity.config.data.httpPort | default .Values.global.nbi.port }}
    redisSvc: {{ .Values.redis.address | quote }}
    nbiPort: {{ .Values.ueIdentity.config.data.nbiPort | default .Values.global.nbi.port }}
    https: {{ .Values.ueIdentity.config.data.https | default .Values.global.https }}
    httpVer: {{ .Values.ueIdentity.config.data.httpVer | default .Values.global.nbi.httpVersion }}
{{- end }}
