{{- if and .Values.services.ueIdentity .Values.ueIdentity.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ue-identity-config
  labels:
    app.kubernetes.io/name: ue-identity
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    httpPort: {{ .Values.ueIdentity.config.data.httpPort }}
    redisSvc: {{ .Values.redis.address | quote }}
    nbiPort: {{ .Values.ueIdentity.config.data.nbiPort }}
    https: {{ .Values.ueIdentity.config.data.https }}
    httpVer: {{ .Values.ueIdentity.config.data.httpVer }}
{{- end }}
