{{- if and .Values.prometheus.enabled .Values.prometheus.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
{{ toYaml .Values.prometheus.config.data | indent 4 }}
{{- end }}
