{{- if and .Values.trafficInfluence.enabled .Values.trafficInfluence.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-traffic-influence-config
  labels:
    app.kubernetes.io/name: traffic-influence
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
{{ toYaml .Values.trafficInfluence.config.data | indent 4 }}
{{- end }}
